### ISSUE TITLE
Rename tags

### ISSUE THREAD

**Issue by edelgrace** [tomatoes-app/tomatoes#104]
I didn't click enough links. I found how to do it. Sorry, sorry!

Sometimes I misspell a tag by accident and don't notice it until I look at all of my tags. I  would love to be able to rename tags to have accurate statistics.

**Comment by antgel** [comment]
Um, how did you do this? I click on a tag and there is no "Edit" option.

**Comment by edelgrace** [comment]
> Um, how did you do this? I click on a tag and there is no "Edit" option.

You actually have to click on your tomato and then you can edit the tags associated with the tomato. Unfortunately, you cannot not rename the tag itself. You will have to find all tomatoes with that tag and edit them.

**Comment by antgel** [comment]
Thanks. @potomak What's the chances of adding a "rename tag" feature?

**Comment by potomak** [comment]
Hello,

The chances of such a feature are low.

According to the current data model, tags are stored in each tomato, so,
even if it would be possible, it wouldn’t be efficient to rename all
occurrences of a tag.

I would suggest you to create a project that includes all tags you care
(old and new name).
