### ISSUE TITLE
Option to re-alarm if no pomodoro has started

### ISSUE THREAD

**Issue by rschuetzler** [tomatoes-app/tomatoes#109]
If I am called away from my desk, often during a break, I often forget to start a new pomodoro when I get back. If I could be periodically reminded that I'm still in the break period, that would be helpful.

**Comment by amrtn** [comment]
+1

**Comment by potomak** [comment]
@rschuetzler, and all the other people following this issue, I released version 0.13 that includes a solution for this issue.
