### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by canercandan** [tomatoes-app/tomatoes#128]
Create a docker image that helps to deploy tomatoes much more easily.

**Comment by potomak** [comment]
Note: Tomatoes docker image could be very similar to Errbit's one, they both are Rails app that use MongoDB as a storage engine.

Some resources:

* http://blog.kontena.io/dockerizing-ruby-application/
* https://github.com/griff/errbit-docker

**Comment by potomak** [comment]
@canercandan would you like to help us by submitting a PR that includes a `Dockerfile` and a document with some instructions on how to setup the app?

**Comment by potomak** [comment]
@morrme this would need a lot of help. I'm not a Docker expert. What do you think?

**Comment by morrme** [comment]
@potomak i am researching this now.

**Comment by potomak** [comment]
Thanks @morrme, let me know if I can help.

The main goal for this issue would be to come up with a Dockerfile that contains the configuration to run the project against the latest version of Docker, that seems to be v17.03.

**Comment by potomak** [comment]
Note: the main requirement for the container to work would be to be _linked_ against a container containing MongoDB. I wouldn't like to include MongoDB in the same container as the app.

**Comment by morrme** [comment]
That was my next question!

**Comment by MathijsHoogland** [comment]
Hi guys, if nobody is working on this issue I'd like to pick it up and submit a PR. What's the status of your research @morrme? ;)

**Comment by potomak** [comment]
Go for it @MathijsHoogland!

Tomatoes app Dockerfile is going to be pretty straightforward, the interesting part is the docker compose configuration to link it with a mongodb container.

Another improvement that this task should introduce is using env variables to configure third party API clients as opposed as the configuration files approach that's being used right now.

**Comment by potomak** [comment]
@MathijsHoogland any news?

**Comment by Ruben-E** [comment]
Hi! Noticed that this issue is already open for quite a long time. I started working on this. 
Well, progress so far: Dockerfile has been created and works already (installing dependencies, gems, setting environment variables ect.). However, there are still issues with serving the assets. Trying to fix these too.
