### ISSUE TITLE
Hide Tomatoes authorizations

### ISSUE THREAD

**Issue by potomak** [tomatoes-app/tomatoes#200]
![screenshot_20161103-082353](https://cloud.githubusercontent.com/assets/153842/19965788/031b8f10-a19f-11e6-8d73-bf3a37d8e382.png)

**Comment by potomak** [comment]
This also relates to https://github.com/potomak/tomatoes/issues/203 that have been solved by https://github.com/potomak/tomatoes/pull/204.

**Comment by bugant** [comment]
@potomak can you, please, elaborate more on this?

**Comment by potomak** [comment]
@bugant `users/show.html.erb` includes a list of authorization urls (https://github.com/tomatoes-app/tomatoes/blob/12bf678416896a055c4524ed805652ab5e0da58e/app/views/users/show.html.erb#L19-L21):

```html+ruby
<% @user.authorizations.each do |authorization| %>
  <%= link_to authorization.url, authorization.url %><br/>
<% end %>
```

This list includes Tomatoes API auth tokens, but they should not be displayed.
