### ISSUE TITLE
Update form errors style

### ISSUE THREAD

**Issue by potomak** [tomatoes-app/tomatoes#226]
After https://github.com/potomak/tomatoes/pull/220 form errors should be updated to follow Bootstrap's style. Maybe we could introduce https://github.com/plataformatec/simple_form to refactor forms and include per field errors.

**Comment by madeindjs** [comment]
You can also consider [rails-bootstrap-forms](https://github.com/bootstrap-ruby/rails-bootstrap-forms) gem. I can eventually trie to implement it later?

**Comment by matjack1** [comment]
I think this issue should be closed as it's been addressed in #299, or at least I cannot find any missing error fields. If there are any known I would be happy to help out :)

**Comment by potomak** [comment]
I think you're right, thanks @matjack1.
