### ISSUE TITLE
Installation instructions.

### ISSUE THREAD

**Issue by Darksider3** [tomatoes-app/tomatoes#257]
Just where curious: How to install this?^^Found it today.

I grepped some dependencies out of Travis, and then installed all trough bundle, but to list all *necessary* ones i would need to understand ruby(which i can't).

I put all together into an install.md: https://gist.github.com/Darksider3/9c22e73b406857716c894eccd9cd82fb
It's still only a skeletton. But maybe u have some additions? At best, a list of the dependencies or better, how i have to read the `Gemfile` to grock it myself.

Thanks.

PS: I know my english isn't the best one out there. Please excuse some fails.^^'

PPS: This ticket and the skeletton needed 2 tomatoes.
PPPS: The P/PP/PPPS section needed exclusivly 0.173 tomatoes.

**Comment by potomak** [comment]
Thanks for your help. I'd suggest using rbenv or rvm to install ruby, but in general I agree with the steps you came up in the gist. Another approach to make it easier to start working on the project would be to include a Dockerfile, see https://github.com/tomatoes-app/tomatoes/issues/128. @Darksider3 would you like to create a PR where you put the foundations for an `INSTALL.md` document?

**Comment by Darksider3** [comment]
Of course. I'll Open a PR in a few hours.
