### ISSUE TITLE
Add app smart banner

### ISSUE THREAD

**Issue by potomak** [tomatoes-app/tomatoes#268]
Now that the prototype app has been published we could add the smart app banner.

See https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html.

**Comment by morrme** [comment]
I'd like to help with this. Which file(s) would need to be updated?

**Comment by potomak** [comment]
@morrme you'd need to add a new meta tag in [`app/views/layouts/default.html.erb`](https://github.com/tomatoes-app/tomatoes/blob/master/app/views/layouts/default.html.erb#L21) right before the `stylesheet_link_tag` instruction.

The meta tag:

```html
<meta name="apple-itunes-app" content="app-id=1205320957" />
```

**Comment by morrme** [comment]
@potomak do you have an affiliate string as well?

**Comment by potomak** [comment]
@morrme no, the id is enough.

**Comment by potomak** [comment]
Closed by https://github.com/tomatoes-app/tomatoes/pull/282.
