### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by reubenjlyons** [tomatoes-app/tomatoes#293]
Time is wrong on my version of the app. Always an hour behind with the right minutes!

**Comment by potomak** [comment]
@reubenjlyons did you set your time zone?

To do so:

1. log in
1. go to your profile, by clicking on your name on the top right corner of the screen
1. edit your profile, by clicking on the "Edit profile" button
1. choose the correct time zone
1. save

**Comment by reubenjlyons** [comment]
Thank you it worked ! Haha

Reuben Lyons
