### ISSUE TITLE
The tomato.es web site is down!

### ISSUE THREAD

**Issue by ntc2** [tomatoes-app/tomatoes#340]
Or maybe it's a DNS issue: no `A` record returned by `dig tomato.es @8.8.8.8`!

**Comment by maplebar** [comment]
I see the backerpass page is down too.  
https://www.backerpass.com/tomatoes

Is @potomak shutting down this project?

**Comment by SOGSDeptutySpeaker** [comment]
I really hope this project isn't shutting down - I use it almost everyday and it's SO important to my work!!

**Comment by gabrielkrell** [comment]
I'd hope potomak would give us a couple days to export CSVs, at least

**Comment by antgel** [comment]
I tweeted about it hoping for a response. Sad.

**Comment by potomak** [comment]
Sorry for the late reply and for the inconvenience.

I’m not working on the project anymore.

I will try to make data available for download before the end of the year.

**Comment by potomak** [comment]
I updated the GitHub app.

You get access to your account by connecting to http://tomatoes2.herokuapp.com.

**Comment by potomak** [comment]
I updated the Twitter app too.

Now you can access your account using Twitter and GitHub.

Please download your data. I'm not sure I'm going to be able to support the project in the future.

Thanks

**Comment by ntc2** [comment]
@potomak thanks for making our data available for download, and thanks for all your hard work on the project over the years!

Everyone else, since tomato.es has gone away I've been using https://pomofocus.io/ which works fine for my purposes. Curios what other alternatives people have found and liked.

**Comment by antgel** [comment]
@ntc2 Thanks for the recommendation! I've gone mobile for flexibility, using Goodtime, open source and minimal.
