### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by canercandan** [tomatoes-app/tomatoes#69]
I have no idea to do it with ruby. But add it as a long-term feature.

**Comment by rulrok** [comment]
I can help with Brazilian Portuguese translations.

**Comment by potomak** [comment]
I'd like to start working on this issue. It shouldn't be hard to solve using Rails I18n module. The only other sections that should be localized are static pages.

**Comment by potomak** [comment]
#266 partially solves this issue.

The next step is starting to write translations files, translating static pages, and maybe adding a way to link pages in a specific language, e.g. using a segment in the path.

**Comment by potomak** [comment]
@rulrok are you still interested in helping translating the app in Brazilian Portuguese?

**Comment by potomak** [comment]
@epatarroyo are you still interested in helping translating the app in Spanish and/or French?

**Comment by rulrok** [comment]
@potomak Sure. But I only have time to translate assets. No actual time to program more complicated stuff.

**Comment by potomak** [comment]
@rulrok that's perfect!

Things to do start translating Tomatoes:

1. add the locale to the list of supported locales in [`config/application.rb`](https://github.com/tomatoes-app/tomatoes/blob/0.14.0/config/application.rb#L30)
1. create a new local configuration in `config/locales`, you can start by copying the [`config/locales/en.yml`](https://github.com/tomatoes-app/tomatoes/blob/0.14.0/config/locales/en.yml) locale configuration

You need to do this in a new fork and submit a PR for the update to be included in the main repo.

**Comment by epatarroyo** [comment]
@potomak sure, I will try to do something this week.
